### ISSUE TITLE
Axios interceptor runs more and more on each page load

### ISSUE THREAD

**Issue by dshiells** [Dattaya/isomorphic-redux-plus#1]
The Axios interceptor in server.js is run more and more on each page load. On first load it is run twice, four times the next load, then six, then eight etc.

It seems it runs all previous requests as well as the current one. The final one must be the one that returns a result as this sets all cookies etc meaning if you login in from multiple browser sessions the same user is always logged in.

Is there any way around this?

**Comment by Dattaya** [comment]
Hi, @dshiells! This repository is very outdated and has a bug with axios on the backend. I'm sorry for not fixing all of this sooner. I'm going to improve the code withing a few days.

**Comment by Dattaya** [comment]
Now a new axios instance is created on each request: https://github.com/Dattaya/isomorphic-redux-plus/blob/master/src/server/server.js#L49. Please, let me know if it solves the problem. Another changes:
- Updated all the dependencies to their latest versions, including React to v.15
- Now there are two config files, one—common, another—only for the backend
- Compile stage includes compiling with babel for the server, because babel-register is not meant for production in babel 6
- This project could be used with redux dev tools chrome extension
- react-router-redux has been integrated
- API errors are handled better (allow the server to return any status if an api error occurs, not just 404).
- For linting `eslint-config-airbnb` is used

List of commits: https://github.com/Dattaya/isomorphic-redux-plus/commits/master

What is planned next: 
- [x] Fixing all linting errors
- [x] Prettifying the code
- [x] Describing the difference between this repo and `isomorphic-redux` and how it works, 
- [ ] Adding more jsdoc and inline comments
- [ ] Creating a `real-worldish` branch with `webpack-isomorphic-tools`, tweaks for better performance (more requests per second), CSRF protection, connection to MongoDB, and so on
- [ ] Another branch that is ready to be deployed to OpenShift

As usual, feedback is welcome, if you have any questions, I will be glad to answer them.

**Comment by Dattaya** [comment]
First three tasks on the todo list are done, I described the differences between this and `isomorphic-redux` repos here: https://github.com/bananaoomarang/isomorphic-redux/issues/26#issuecomment-224235216
Closing this issue as I hope the problem with axios was resolved.
